{
 "title": "Bank Recs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Top Recommendation Confidence",
   "type": "stat",
   "description": "Median (50th percentile) confidence of the model's top product recommendations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(recommender_top_probability_bucket[20m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model Mean Log Loss",
   "type": "gauge",
   "description": "Metrics of model performance (the lower the better)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "recommender_model_mean_log_loss",
     "legendFormat": "Number of recs per request"
    }
   ]
  },
  {
   "title": "Number of Requests in Progress",
   "type": "stat",
   "description": "Active HTTP requests being processed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "recommender_inprogress_requests{endpoint=\"/predict\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Number of Predictions Made over Past 24h",
   "type": "stat",
   "description": "Successful predictions in last 24 hours",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(recommender_requests_total{status=\"success\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Predictions Number per 1 Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(recommender_requests_total{status=\"success\"}[1m])",
     "legendFormat": "Number of predictions (requests/min (1m))"
    }
   ]
  },
  {
   "title": "Requests per Minute by Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(recommender_requests_total[5m])",
     "legendFormat": "{{endpoint}}_{{status}}"
    }
   ]
  },
  {
   "title": "Average Prediction Latency",
   "type": "gauge",
   "description": "Mean of prediction latency over requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(recommender_prediction_latency_seconds_sum[5m])) / \r\nsum(rate(recommender_prediction_latency_seconds_count[5m])) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction Latency Distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(recommender_prediction_latency_seconds_bucket[5m])) by (le)",
     "legendFormat": "{{le}} ms "
    }
   ]
  },
  {
   "title": "HTTP Requests Error Rate per 1 Minute by Error Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"4..|5..\"}[1m])) by (status)"
    }
   ]
  },
  {
   "title": "Average HTTP Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[1m])) / sum(rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "Average request latency over 1 minute (in sec)"
    }
   ]
  }
 ]
}